#!/usr/bin/env python3
"""Generate paper-facing LaTeX tables from artifact-backed files."""

from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LATEX_TABLES = ROOT / "paper" / "latex" / "tables"
FORMAL_JSON = ROOT / "artifacts" / "formal_protocol_validation.json"
MAIN_RESULTS_TEX = ROOT / "paper" / "tables" / "main_results.tex"
ABLATION_CSV = ROOT / "paper" / "figures" / "data" / "ablation_waterfall_data.csv"
FAILURE_BUCKET_CSV = ROOT / "paper" / "figures" / "data" / "failure_bucket_delta.csv"
CLONEMEM_EFFICIENCY_JSON = (
    ROOT.parent
    / "BenchmarkResult"
    / "manual_clonemem_efficiency_v2_20260430_134155"
    / "clonemem"
    / "clonemem"
    / "merged_metrics.json"
)


def esc(value: object) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def fmt(value: object, places: int = 4) -> str:
    if value in ("", None):
        return "--"
    try:
        return f"{float(value):.{places}f}"
    except (TypeError, ValueError):
        return esc(value)


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.rstrip() + "\n")


def load_formal() -> dict:
    return json.loads(FORMAL_JSON.read_text())


def generate_main_results(formal: dict) -> None:
    rows = []
    for item in formal["full_benchmarks"]:
        metrics = item["metrics"]
        admission = metrics.get("candidate_recall@100")
        final = metrics.get("final_recall@10") or metrics.get("recall_frac@10")
        gap = None
        if admission is not None and final is not None:
            gap = admission - final
        rows.append(
            [
                item["benchmark"],
                "DysonSpherain formal full",
                item["question_count"],
                item["elapsed_seconds"],
                admission,
                final,
                gap,
                metrics.get("final_ndcg@10") or metrics.get("ndcg_any@10"),
                item.get("run_id", ""),
                item.get("comparison_status", ""),
                item["status"],
            ]
        )
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from artifacts/formal_protocol_validation.json.",
        r"\begin{tabular}{llrrrrrll}",
        r"\toprule",
        r"Benchmark & System & Q & Admission R@100 & Final R@10 & Gap & NDCG@10 & Run ID & Status \\",
        r"\midrule",
    ]
    for row in rows:
        body.append(
            f"{esc(row[0])} & {esc(row[1])} & {row[2]} & {fmt(row[4])} & {fmt(row[5])} & {fmt(row[6])} & {fmt(row[7])} & {esc(row[8])} & {esc(row[10])} \\\\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "main_results.tex", "\n".join(body))


def parse_metric_blob(blob: str) -> dict[str, float]:
    metrics: dict[str, float] = {}
    for key, value in re.findall(r"([A-Za-z_@0-9]+)=([0-9.]+)", blob):
        try:
            metrics[key] = float(value)
        except ValueError:
            pass
    return metrics


def parse_baseline_table() -> list[dict[str, object]]:
    rows = []
    pattern = re.compile(r"^([^&]+)&([^&]+)&([^&]+)&(.+)\\\\$")
    for line in MAIN_RESULTS_TEX.read_text().splitlines():
        line = line.strip()
        match = pattern.match(line)
        if not match:
            continue
        benchmark, method, status, metrics_blob = [part.strip() for part in match.groups()]
        if benchmark == "Benchmark":
            continue
        rows.append(
            {
                "benchmark": benchmark,
                "method": method,
                "status": status,
                "metrics": parse_metric_blob(metrics_blob),
            }
        )
    return rows


def best_recall_metric(metrics: dict[str, float]) -> float | None:
    for key in ("final_recall@10", "recall_frac@10", "recall_any@10", "Recall@10", "recall@10"):
        if key in metrics:
            return metrics[key]
    return None


def best_ndcg_metric(metrics: dict[str, float]) -> float | None:
    for key in ("final_ndcg@10", "ndcg_any@10", "NDCG@10", "ndcg@10"):
        if key in metrics:
            return metrics[key]
    return None


def generate_baseline_comparison() -> None:
    allowed_methods = ["bm25", "dense_only_minilm", "dense_bm25_rrf", "dysonspherain_full"]
    baseline_rows = [
        row
        for row in parse_baseline_table()
        if row["method"] in allowed_methods and row["status"] == "available"
    ]
    formal = load_formal()
    formal_by_benchmark = {
        item["benchmark"]: item for item in formal["full_benchmarks"]
    }
    rows = []
    for row in baseline_rows:
        metrics = dict(row["metrics"])
        if row["method"] == "dysonspherain_full":
            item = formal_by_benchmark.get(row["benchmark"])
            if item:
                metrics = dict(item["metrics"])
                row = {
                    **row,
                    "method": "dysonspherain_formal_full",
                    "run_id": item.get("run_id", ""),
                    "comparison": item.get("comparison_status", ""),
                    "elapsed": item.get("elapsed_seconds"),
                }
        rows.append({**row, "metrics": metrics})
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from paper/tables/main_results.tex.",
        r"% DysonSpherain rows are overwritten from artifacts/formal_protocol_validation.json to keep formal full metrics consistent.",
        r"% Missing baseline Admission R@100 means the source artifact did not record candidate-recall diagnostics.",
        r"\begin{tabular}{llrrrrll}",
        r"\toprule",
        r"Benchmark & Method & Admission R@100 & Recall@10 & NDCG@10 & Elapsed s & Comparability & Run ID \\",
        r"\midrule",
    ]
    for row in rows:
        metrics = row["metrics"]
        comparability = row.get("comparison") or "available; admission may be unrecorded"
        body.append(
            f"{esc(row['benchmark'])} & {esc(row['method'])} & {fmt(metrics.get('candidate_recall@100'))} & {fmt(best_recall_metric(metrics))} & {fmt(best_ndcg_metric(metrics))} & {fmt(row.get('elapsed'), 1)} & {esc(comparability)} & {esc(row.get('run_id', ''))} \\\\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "baseline_comparison.tex", "\n".join(body))


def load_ablation_rows() -> dict[tuple[str, str], dict[str, float]]:
    out: dict[tuple[str, str], dict[str, float]] = defaultdict(dict)
    with ABLATION_CSV.open() as f:
        for row in csv.DictReader(f):
            if row["status"] != "available":
                continue
            try:
                out[(row["benchmark"], row["ablation"])][row["metric"]] = float(row["value"])
            except ValueError:
                continue
    return out


def generate_ablation_results() -> None:
    data = load_ablation_rows()
    ablations = [
        "full_admission",
        "no_route_conditioned_admission",
        "no_lexical_probe",
        "no_temporal_routing",
        "no_parent_to_segment_selector",
        "no_safe_fusion",
    ]
    labels = {
        "full_admission": "Full",
        "no_route_conditioned_admission": "-Route",
        "no_lexical_probe": "-Lexical",
        "no_temporal_routing": "-Temporal",
        "no_parent_to_segment_selector": "-Parent2Seg",
        "no_safe_fusion": "-SafeFusion",
    }
    interpretations = {
        "no_route_conditioned_admission": "route policy sensitivity",
        "no_lexical_probe": "lexical route can help anchors or add noise",
        "no_temporal_routing": "temporal route is surface-dependent",
        "no_parent_to_segment_selector": "parent-to-segment selection risk",
        "no_safe_fusion": "dense protection tradeoff",
    }
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from paper/figures/data/ablation_waterfall_data.csv.",
        r"% Deltas are against the ablation-family full_admission row, not against the formal full run.",
        r"\begin{tabular}{llrrrl}",
        r"\toprule",
        r"Benchmark & Removed Module & $\Delta$Admission R@100 & $\Delta$Final R@10 & $\Delta$NDCG@10 & Interpretation \\",
        r"\midrule",
    ]
    for benchmark in sorted({key[0] for key in data}):
        full_metrics = data.get((benchmark, "full_admission"), {})
        for ablation in ablations[1:]:
            metrics = data.get((benchmark, ablation), {})
            if not metrics:
                continue
            d_adm = None
            d_rec = None
            d_ndcg = None
            if "candidate_recall@100" in full_metrics and "candidate_recall@100" in metrics:
                d_adm = metrics["candidate_recall@100"] - full_metrics["candidate_recall@100"]
            full_rec = full_metrics.get("final_recall@10", full_metrics.get("recall_frac@10"))
            rec = metrics.get("final_recall@10", metrics.get("recall_frac@10"))
            if full_rec is not None and rec is not None:
                d_rec = rec - full_rec
            full_ndcg = full_metrics.get("final_ndcg@10", full_metrics.get("ndcg_any@10"))
            ndcg = metrics.get("final_ndcg@10", metrics.get("ndcg_any@10"))
            if full_ndcg is not None and ndcg is not None:
                d_ndcg = ndcg - full_ndcg
            body.append(
                f"{esc(benchmark)} & {esc(labels[ablation])} & {fmt(d_adm)} & {fmt(d_rec)} & {fmt(d_ndcg)} & {esc(interpretations[ablation])} \\\\"
            )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "ablation_results.tex", "\n".join(body))


def generate_route_policy_table(formal: dict) -> None:
    params = [
        ("dense_top_k", "dense_top_k"),
        ("protected_dense_top_m", "dense_anchor_top_k"),
        ("lexical_top_k", "lexical_top_k"),
        ("temporal_top_k", "temporal_top_k"),
        ("parent_top_k", "parent_top_k"),
        ("child_segment_cap", "parent_expand_segments"),
        ("final_k", "candidate_recall_eval_k"),
        ("fusion", "fusion_method"),
        ("duplicate_cap", "max_candidates_per_parent"),
        ("route_policy_hash", "route_policy_hash"),
    ]
    by_benchmark = {}
    for item in formal["full_benchmarks"]:
        artifact_dir = Path(item["artifact_dir"])
        metrics_path = artifact_dir / "merged_metrics.json"
        if not metrics_path.exists():
            metrics_path = artifact_dir / "metrics.json"
        effective = {}
        route_hash = item.get("route_policy_hash") or ""
        if metrics_path.exists():
            try:
                data = json.loads(metrics_path.read_text())
                effective = (
                    data.get("route_policy_config", {}).get("effective_policy", {})
                    or data.get("runtime_config", {}).get("clonemem_route_policy", {})
                    or {}
                )
                route_hash = data.get("route_policy_hash") or route_hash
            except Exception:
                effective = {}
        effective["route_policy_hash"] = route_hash
        by_benchmark[item["benchmark"]] = effective

    benchmarks = [item["benchmark"] for item in formal["full_benchmarks"]]
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from formal artifact metric files.",
        r"\begin{tabular}{lllll}",
        r"\toprule",
        r"Parameter & LongMemEval & LoCoMo & KnowMe & CloneMem \\",
        r"\midrule",
    ]
    name_map = {"longmemeval": "LongMemEval", "locomo": "LoCoMo", "knowme": "KnowMe", "clonemem": "CloneMem"}
    for label, key in params:
        cells = []
        for bench in ["longmemeval", "locomo", "knowme", "clonemem"]:
            value = by_benchmark.get(bench, {}).get(key)
            cells.append(esc(value if value not in (None, "") else "not recorded"))
        body.append(f"{esc(label)} & " + " & ".join(cells) + r" \\")
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "route_policy_hyperparameters.tex", "\n".join(body))


def generate_failure_taxonomy() -> None:
    counts: dict[tuple[str, str], int] = defaultdict(int)
    with FAILURE_BUCKET_CSV.open() as f:
        for row in csv.DictReader(f):
            counts[(row["benchmark"], row["ablation"])] += 1
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from paper/figures/data/failure_bucket_delta.csv.",
        r"\begin{tabular}{llr}",
        r"\toprule",
        r"Benchmark & Ablation & Artifact Rows \\",
        r"\midrule",
    ]
    for (benchmark, ablation), count in sorted(counts.items()):
        body.append(f"{esc(benchmark)} & {esc(ablation)} & {count} \\\\")
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "failure_taxonomy.tex", "\n".join(body))


def generate_artifact_validation_summary(formal: dict) -> None:
    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from artifacts/formal_protocol_validation.json.",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Evidence Section & Available & Blocked & Pending & Total \\",
        r"\midrule",
    ]
    for section, stats in formal["evidence_sections"].items():
        body.append(
            f"{esc(section)} & {stats['available']} & {stats['blocked']} & {stats['pending']} & {stats['total']} \\\\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write(LATEX_TABLES / "artifact_validation_summary.tex", "\n".join(body))


def nested(data: dict, *keys: str) -> object:
    current: object = data
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def generate_clonemem_efficiency_table(formal: dict) -> None:
    formal_clone = next((item for item in formal["full_benchmarks"] if item["benchmark"] == "clonemem"), {})
    formal_metrics = formal_clone.get("metrics", {})
    rows = [
        (
            "Formal full",
            formal_clone.get("question_count"),
            formal_clone.get("elapsed_seconds"),
            None,
            formal_metrics.get("candidate_recall@100"),
            formal_metrics.get("final_recall@10") or formal_metrics.get("recall_frac@10"),
            formal_metrics.get("final_ndcg@10") or formal_metrics.get("ndcg_any@10"),
        )
    ]
    current_values = None
    note = "Current efficiency artifact not found; only the formal full source-of-truth row is shown."
    if CLONEMEM_EFFICIENCY_JSON.exists():
        current = json.loads(CLONEMEM_EFFICIENCY_JSON.read_text())
        elapsed = current.get("wall_clock_elapsed_seconds") or current.get("elapsed_seconds")
        serial_elapsed = current.get("serial_elapsed_seconds_sum")
        current_values = {
            "formal_elapsed": formal_clone.get("elapsed_seconds"),
            "current_elapsed": elapsed,
            "question_count": current.get("total_question_count") or current.get("question_count"),
            "speedup": current.get("speedup_estimate"),
            "admission": nested(current, "metrics", "candidate_recall@100"),
            "final_recall": nested(current, "metrics", "final_recall@10") or nested(current, "metrics", "recall_frac@10"),
        }
        rows.append(
            (
                "Apr. 30 efficiency",
                current.get("total_question_count") or current.get("question_count"),
                elapsed,
                current.get("speedup_estimate"),
                nested(current, "metrics", "candidate_recall@100"),
                nested(current, "metrics", "final_recall@10") or nested(current, "metrics", "recall_frac@10"),
                nested(current, "metrics", "final_ndcg@10") or nested(current, "metrics", "ndcg_any@10"),
            )
        )
        note = (
            "The efficiency run is official-embedding and Chroma-backed, but it is used as runtime evidence; "
            "quality remains a warning because CloneMem candidate recall is still low."
        )
        if elapsed and serial_elapsed:
            note += f" Serial shard time sums to {fmt(serial_elapsed, 1)} seconds."

    body = [
        r"% Auto-generated by scripts/generate_paper_tables.py from formal validation and the 2026-04-30 CloneMem efficiency artifact.",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Run & Q & Wall s & Speedup & Admission R@100 & Final R@10 & Final NDCG@10 \\",
        r"\midrule",
    ]
    for label, q_count, elapsed, speedup, admission, final_recall, final_ndcg in rows:
        body.append(
            f"{esc(label)} & {fmt(q_count, 0)} & {fmt(elapsed, 1)} & {fmt(speedup, 2)} & {fmt(admission)} & {fmt(final_recall)} & {fmt(final_ndcg)} \\\\"
        )
    body.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            "",
            r"\vspace{2pt}",
            "",
            r"\parbox{0.96\linewidth}{\footnotesize " + esc(note) + r"}",
        ]
    )
    write(LATEX_TABLES / "clonemem_efficiency_optimization.tex", "\n".join(body))
    if current_values:
        text = (
            "The April 30 CloneMem efficiency run reduces full-run wall-clock time from the "
            f"formal source-of-truth row's {fmt(current_values['formal_elapsed'], 1)} seconds to "
            f"{fmt(current_values['current_elapsed'], 1)} seconds on the same "
            f"{fmt(current_values['question_count'], 0)} questions, with a "
            f"{fmt(current_values['speedup'], 2)}$\\times$ shard-level speedup estimate. "
            "This is an engineering result, not a retrieval-quality result: candidate recall at 100 is "
            f"{fmt(current_values['admission'])} and final recall at 10 is "
            f"{fmt(current_values['final_recall'])}, matching the existing CloneMem bottleneck profile. "
            "The manuscript therefore updates the runtime claim while preserving the conclusion that CloneMem remains unsolved."
        )
    else:
        text = (
            "No current full-run CloneMem efficiency artifact is available, so the paper reports only the formal "
            "source-of-truth runtime and does not make a new efficiency claim."
        )
    write(LATEX_TABLES / "clonemem_efficiency_text.tex", text)


def main() -> int:
    formal = load_formal()
    generate_main_results(formal)
    generate_baseline_comparison()
    generate_ablation_results()
    generate_failure_taxonomy()
    generate_artifact_validation_summary(formal)
    generate_clonemem_efficiency_table(formal)
    generate_route_policy_table(formal)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
