#!/usr/bin/env python3
"""Extract anonymized case studies from diagnostic JSONL artifacts."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_TEX = ROOT / "paper" / "latex" / "case_studies.tex"
OUT_TABLE = ROOT / "paper" / "latex" / "tables" / "case_study_examples.tex"
DIAG_DIR = ROOT / "reports" / "diagnostics"


SOURCES = [
    ("Temporal anchoring drift", DIAG_DIR / "clonemem_temporal_miss_examples.jsonl"),
    ("Parent-hit segment miss", DIAG_DIR / "clonemem_parent_hit_segment_miss_examples.jsonl"),
    ("Reranker dropped gold", DIAG_DIR / "reranker_dropped_gold_examples.jsonl"),
    ("KnowMe segment admission failure", DIAG_DIR / "knowme_segment_admission_failures.jsonl"),
]


def esc(text: object) -> str:
    text = "" if text is None else str(text)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def redact(text: str, limit: int = 170) -> str:
    text = re.sub(r"[0-9a-f]{8}-[0-9a-f-]{27,}", "[id]", text, flags=re.I)
    text = re.sub(r"\s+", " ", text).strip()
    text = "".join(ch if ord(ch) < 128 else "[redacted]" for ch in text)
    text = re.sub(r"(?:\[redacted\]){2,}", "[redacted]", text)
    if len(text) > limit:
        text = text[: limit - 3].rstrip() + "..."
    return text


def first_jsonl(path: Path) -> dict | None:
    if not path.exists():
        return None
    with path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                return json.loads(line)
    return None


def summarize_channels(row: dict) -> str:
    hits = row.get("channels_that_hit_gold") or []
    if hits:
        return ", ".join(hits[:4])
    stats = row.get("channel_stats") or {}
    return ", ".join(name for name, info in stats.items() if info.get("gold_hit")) or "none"


def main() -> int:
    rows = []
    for label, path in SOURCES:
        row = first_jsonl(path)
        if row:
            row["case_label"] = label
            rows.append(row)

    table = [
        r"% Auto-generated by scripts/generate_case_studies.py from reports/diagnostics/*.jsonl.",
        r"\begin{tabular}{lrrrrrl}",
        r"\toprule",
        r"Case & Dense Rank & Fused Rank & Parent Rank & Segment Rank & Final Rank & Fixed By \\",
        r"\midrule",
    ]
    for i, row in enumerate(rows, 1):
        stats = row.get("channel_stats", {})
        parent_rank = (stats.get("parent_session") or {}).get("gold_rank")
        dense_rank = row.get("dense_gold_rank")
        fused_rank = row.get("fused_gold_rank")
        final_rank = row.get("gold_rank_after_rerank")
        segment_rank = row.get("gold_rank_before_rerank")
        fixed_by = "not fixed" if row.get("final_recall@10") == 0.0 else "final retrieval"
        table.append(
            f"{i}. {esc(row['case_label'])} & {esc(dense_rank or '--')} & {esc(fused_rank or '--')} & {esc(parent_rank or '--')} & {esc(segment_rank or '--')} & {esc(final_rank or '--')} & {esc(fixed_by)} \\\\"
        )
    table.extend([r"\bottomrule", r"\end{tabular}"])
    OUT_TABLE.parent.mkdir(parents=True, exist_ok=True)
    OUT_TABLE.write_text("\n".join(table) + "\n")

    sections = [
        r"% Auto-generated by scripts/generate_case_studies.py.",
        r"\subsection{Diagnostic Case Studies}",
        r"The examples below are extracted from diagnostic JSONL artifacts and redacted/truncated for paper use. They illustrate failure attribution rather than new benchmark claims.",
    ]
    for i, row in enumerate(rows, 1):
        sections.append(f"\\paragraph{{Case {i}: {esc(row['case_label'])}.}}")
        sections.append(
            f"Benchmark: \\texttt{{{esc(row.get('benchmark_name'))}}}. Failure type: \\texttt{{{esc(row.get('failure_type'))}}}. "
            f"Admission R@100 for the query is {row.get('candidate_recall@100')}; final R@10 is {row.get('final_recall@10')}. "
            f"Dense rank: {esc(row.get('dense_gold_rank') or '--')}; fused rank: {esc(row.get('fused_gold_rank') or '--')}; final rank: {esc(row.get('gold_rank_after_rerank') or '--')}. "
            f"Gold-hitting channels: {esc(summarize_channels(row))}. "
            f"Query excerpt: ``{esc(redact(row.get('query_text', '')))}''"
        )
    OUT_TEX.write_text("\n\n".join(sections) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
